name: liquid_widgets
description: "A Flutter package for creating iOS-style liquid glass UI widgets with blur effects, gradient borders, and subtle shadows."
version: 1.0.0
homepage: https://github.com/alisheraxmedov/liquid_widgets
repository: https://github.com/alisheraxmedov/liquid_widgets
issue_tracker: https://github.com/alisheraxmedov/liquid_widgets/issues

environment:
  sdk: ^3.5.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
